# -*- coding: utf-8 -*-
"""prediksipenyakitparu-paru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xO6t-U-I3CFUkKHL9aWF9idn7jz9Y07
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('predic_tabel.csv')
data.head(10)

data.drop(columns=['No'], inplace=True)
data.head(10)

data.isnull().sum()

df = pd.DataFrame(data)
column = ['Usia','Jenis_Kelamin','Merokok','Bekerja','Rumah_Tangga','Aktivitas_Begadang','Aktivitas_Olahraga','Asuransi','Penyakit_Bawaan','Hasil']
label_encoder = LabelEncoder()
for col in column:
  df[col] = label_encoder.fit_transform(df[col])
df.head(10)

x = df.drop(['Hasil'], axis=1)
x.head(10)

y = df['Hasil']
y.head(10)

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

nbc = GaussianNB()
data_training = nbc.fit(x_train,y_train)

y_predict = data_training.predict(x_test)
print(y_predict[:10])

Usia = 0 # Muda
Jenis_Kelamin = 0 # Pria
Merokok = 1 # Pasif
Bekerja = 0 # Tidak
Rumah_Tangga = 0 # Tidak
Aktivitas_Begadang = 1 # Ya
Aktivitas_Olahraga = 0 # Jarang
Asuransi = 1 # Tidak
Penyakit_Bawaan = 1 # Tidak

Data_Testing = [[Usia,Jenis_Kelamin,Merokok,Bekerja,Rumah_Tangga,Aktivitas_Begadang,Aktivitas_Olahraga,Asuransi,Penyakit_Bawaan]]
y_pred = (Data_Testing)

if y_pred == 0:
  Hasil = 'Ya'
elif y_pred == 1:
  Hasil = 'Tidak'
else:
  Hasil = 'ya'

print("Hasil Prediksi Penyakit Terjangkit Paru-paru Adalah : ", Hasil)